[package]
name = "rocket_fortune"
version = "0.5.0"
authors = ["SilverWingedSeraph <lfstindall@gmail.com>"]

[dependencies]
rocket = "0.1.4"
rocket_codegen = "0.1.4"

rand = "0.3.15"
rusqlite = "0.8.0"

serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"

[dependencies.rocket_contrib]
version = "0.1.4"
default_features = false
features = ["tera_templates", "json"]
