[package]
name = "rocket_fortune"
version = "0.1.0"
authors = ["SilverWingedSeraph <lfstindall@gmail.com>"]

[dependencies]
rocket = "0.1.3"
rocket_codegen = "0.1.3"

rand = "*"
rusqlite = "0.8.0"

serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
