[development]
databases.sqlite = { url = "dev.db" }

# NOTE: Do NOT !!! !!! use these keys; instead generate random keys
# for example with
# dd if=/dev/urandom bs=24 count=1 | base64 >> key.b64
# and copy and paste here. Must be 24 bytes base64 encoded.

[staging]
session_key = "RAdUdcco7SwzbyWxd8UOkM5ekezIRjsO"
databases.sqlite = { url = "stage.db" }

[production]
address = "0.0.0.0"
port = 80
session_key = "Xu2sLzKhBOxj3TXlFcZooLeooQMp5V0m"
databases.sqlite = { url = "prod.db" }

